In [ ]:
import numpy as np

In [ ]:
x_train = np.array([0., 1, 2, 3, 4, 5],dtype=np.longdouble)
y_train = np.array([0,  0, 0, 1, 1, 1],dtype=np.longdouble)

In [ ]:
class LogisticRegression:
  def __init__(self):
    self.w = 0
    self.b = 0

  def predict(self, X: np.ndarray):
    return self.sigmoid(X.dot(self.w) + self.b)

  def sigmoid(self,prediction: np.ndarray):
    z = 1/(1+np.exp(-prediction))
    return z

  def computeCost(self, X: np.ndarray, y:np.ndarray):
    m = X.shape[0] #no of rows of X
    prediction = X.dot(self.w) + self.b #making prediction with weights
    prediction = self.sigmoid(prediction) #maping the prediction to 0 or 1
    cost = np.sum((y*np.log(prediction))+ ((1-y)*np.log(1-prediction))) #computing the losses
    cost = (1/m) * -cost  #computing the total cost
    return cost

  def fit(self, X: np.ndarray, y:np.ndarray, alpha:int, epochs: int):
    y = y.reshape(-1,1)
    m = X.shape[1]
    self.w = np.zeros((m,1))

    for i in range(epochs):
      cost = self.computeCost(X,y)
      if i%100 ==0:
        print(f"Epoch: {i+1}, Loss: {cost}")
      prediction = self.predict(X)
      error = prediction - y
      gradient = np.dot(X.transpose(),error)
      self.w -= alpha * 1/m * gradient
      self.b -= alpha * 1/m * np.sum(error)

    return (self.w,self.b)

In [ ]:
import numpy as np

X = np.array([[0.5, 1.5], [1,1], [1.5, 0.5], [3, 0.5], [2, 2], [1, 2.5]])
y = np.array([0, 0, 0, 1, 1, 1])

In [ ]:
X,y

(array([[0.5, 1.5],
        [1. , 1. ],
        [1.5, 0.5],
        [3. , 0.5],
        [2. , 2. ],
        [1. , 2.5]]),
 array([[0],
        [0],
        [0],
        [1],
        [1],
        [1]]))

In [ ]:
lr = LogisticRegression()

In [ ]:
y = y.reshape(-1,1)

In [ ]:
lr.fit(X,y,1e-7,10000)

Epoch: 1, Loss: 0.6931471805599452
Epoch: 101, Loss: 0.693144472314579
Epoch: 201, Loss: 0.6931417642460218
Epoch: 301, Loss: 0.6931390563542594
Epoch: 401, Loss: 0.6931363486392776
Epoch: 501, Loss: 0.693133641101063
Epoch: 601, Loss: 0.693130933739601
Epoch: 701, Loss: 0.6931282265548777
Epoch: 801, Loss: 0.6931255195468788
Epoch: 901, Loss: 0.6931228127155908
Epoch: 1001, Loss: 0.6931201060609993
Epoch: 1101, Loss: 0.6931173995830902
Epoch: 1201, Loss: 0.6931146932818498
Epoch: 1301, Loss: 0.6931119871572637
Epoch: 1401, Loss: 0.693109281209318
Epoch: 1501, Loss: 0.6931065754379988
Epoch: 1601, Loss: 0.6931038698432919
Epoch: 1701, Loss: 0.6931011644251832
Epoch: 1801, Loss: 0.6930984591836588
Epoch: 1901, Loss: 0.6930957541187046
Epoch: 2001, Loss: 0.6930930492303068
Epoch: 2101, Loss: 0.693090344518451
Epoch: 2201, Loss: 0.6930876399831234
Epoch: 2301, Loss: 0.69308493562431
Epoch: 2401, Loss: 0.6930822314419967
Epoch: 2501, Loss: 0.6930795274361692
Epoch: 2601, Loss: 0.6930768236

(array([[0.00074885],
        [0.00049907]]),
 -6.709003463317607e-07)